[package]
name = "stateful_gatekeeper"
version = "1.0.0"

[addresses]
stateful_gatekeeper = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "7f900aa660b13bb674924f279f1fd7d55e0cf79e"
subdir = "aptos-move/framework/aptos-framework"
